### ISSUE TITLE
Countries checklist

### ISSUE THREAD

**Issue by jamiegcan** [GoGroGlo/a-place-for-salvador-allende#2]
From the site map http://www.abacq.org/calle/index.php?toc/toc:
- [x] Angola
- [x] Algeria
- [x] Argentina
- [x] Australia
- [x] Austria
- [x] Belgium
- [x] Bosnia and Herzegovina
- [x] Brazil
- [x] Bulgaria
- [x] Canada
- [x] Chile
- [x] Colombia
- [x] Cuba
- [x] Czechia
- [x] Denmark
- [x] Dominican Republic - no places named after Allende
- [x] Ecuador
- [x] El Salvador
- [x] France
- Refer to #1 
- Chunks of 20 (but we'll do two chunks of 10 first in case there are bugs)
- Exclusions: `[http://www.abacq.org/calle/index.php?2009/05/13/349-salvador-allende-en-francia, http://www.abacq.org/calle/index.php?2007/02/18/2-francia-le-blanc-mesnil, http://www.abacq.org/calle/index.php?2009/12/08/445-victor-jara-francia, http://www.abacq.org/calle/index.php?2007/02/18/56-pablo-neruda-en-francia, http://www.abacq.org/calle/index.php?2007/02/18/22-victor-jara]`
- [x] Germany
- 4 chunks of 10
- Exclusions (done scraping): `http://www.abacq.org/calle/index.php?2007/02/18/23-alemania`
- [x] Guinea-Bissau
- [x] Hungary
- [x] India - no places named after Allende
- [x] Iran - no places named after Allende
- [x] Israel
- [x] Italy
- 3 chunks of 10
- Exclusions (done scraping): `http://www.abacq.org/calle/index.php?2007/02/18/26-italia`
- [x] Luxembourg
- [x] Mexico
- 2 chunks of 10
- Exclusions: `http://www.abacq.org/calle/index.php?2011/09/11/545-un-pueblo-llamado-salvador-allende,http://www.abacq.org/calle/index.php?2007/09/22/105-un-pueblo-llamado-salvador-allende,http://www.abacq.org/calle/index.php?2007/02/18/43-universidad-de-guadalajara`
- Note: There is a Mexican independence hero named Ignacio Allende, so places named just "Allende" are now extra ambiguous
- [x] Mozambique
- [x] Netherlands
- [x] Nicaragua
- [x] North Macedonia
- [x] Pakistan
- [x] Palestine
- [x] Paraguay - no places named after Allende
- [x] Peru
- [x] Portugal
- [x] Republic of the Congo
- [x] Russia
- [x] Saudi Arabia
- [x] Serbia
- [x] Slovakia
- [x] Spain
- 7 chunks of 10
- Exceptions (done scraping): `http://www.abacq.org/calle/index.php?2007/02/18/20-espana`
- [x] Turkey
- [x] United Kingdom
- [x] United States - no places named after Allende
- [x] Uruguay
- [x] Venezuela

**Comment by GoGroGlo** [comment]
Took a while, but this is finally done 🎉
